trigger:
  - main

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-18.04'
variables:
  git_password: $(git_password_env)
  git_username: $(git_username_env)
  git_clone_url: $(git_clone_url_env)

steps:

  - script: |
      echo Starting push to Kudu Repository of App Service
      ECHO GIT CHECKOUT integration
      git checkout -b deployment_branch
      ECHO GIT STATUS
      git status
      git push -f https://$(git_username):$(git_password)@$(git_clone_url) deployment_branch:master
    displayName: 'Push integration to Remote Repository'